name: Generate Snake Animation

on:
  schedule:
    # Her gün gece çalıştırılır
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Private commitlerin de dahil edilmesini sağlar
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated Snake Animation"
          git push
